const OriginalColors = {
    TOAST_ERROR_BACKGROUND_COLOR: "#F44336",
    TOAST_FONT_COLOR: "#ffffff",
    TOAST_INFO_BACKGROUND_COLOR: "#323232",
    TOAST_LINK_COLOR: "#ffffff",
    TOAST_SUCCESS_BACKGROUND_COLOR: "#00ac51",
    TOAST_WARNING_BACKGROUND_COLOR: "#f88400",
    MAIN_TEXT_COLOR:'#ff2415'

};

export const Colors = {
    MAIN_TEXT_COLOR:'#ff2415',
    TOAST_ERROR_BACKGROUND_COLOR: "#F44336",
    TOAST_FONT_COLOR: "#ffffff",
    TOAST_INFO_BACKGROUND_COLOR: "#323232",
    TOAST_LINK_COLOR: "#ffffff",
    TOAST_SUCCESS_BACKGROUND_COLOR: "rgba(0,0,0,0.96)",
    TOAST_WARNING_BACKGROUND_COLOR: "#f88400",
    BACK_GROUND_DARK:"#000",

};


